name: Playwright Test
on:
    push:
        branches: [ main ]
jobs:
    playwrighttests:
        runs-on: ubuntu-latest
        container: 
            image: mcr.microsoft.com/playweight:v1.48.2-focal
            env: 
                ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            - name: Run tests
              run: |
                echo "Start the shopping store application"
                chmod +x ./shopping-store-mac-arm64 &
                echo "Install dependencies from lockfile"
                npm ci
                echo "Run playweight test"
                npm run test:ci

